<?php

class Utils
{
    public static $clientId = '###';
    public static $clientSecret = '###';
    public static $refUrlBase = '###';

    static function getAuthArr($authCode)
    {
        $url = 'https://id.twitch.tv/oauth2/token';
        $data = array(
            'client_id'      => Utils::$clientId,
            'client_secret'    => Utils::$clientSecret,
            'code'       => $authCode,
            'grant_type' => 'authorization_code',
            'redirect_uri'      => Utils::$refUrlBase . 'authRecieve.php',
            'scope' => 'moderation:read'

        );

        $options = array(
            'http' => array(
                'method'  => 'POST',
                'content' => http_build_query($data),
                'header' =>  "Content-type: application/x-www-form-urlencoded\r\n"
            )
        );

        $context  = stream_context_create($options);
        $result = file_get_contents($url, false, $context);
        $response = json_decode($result, true);

        if ($response === FALSE) {
            echo 'Fehler beim holen der Infos!';
        }
        return $response;
    }


    static function getUserInfoEndpoint($access_token)
    {
        $url = 'https://id.twitch.tv/oauth2/userinfo';

        $options = array(
            'http' => array(
                'method'  => 'POST',
                'header' =>  "Authorization: Bearer $access_token\r\n"
            )
        );

        $context  = stream_context_create($options);
        $result = file_get_contents($url, false, $context);
        $response = json_decode($result, true);

        if ($response === FALSE) {
            echo 'Fehler beim holen der Infos!';
        } else {
            return $response;
        }
    }


    static function toggleHookBanChangeEvent($subscribe, $userId, $appToken)
    {
        // Das scheint mit file_get_contents nicht zu funktionieren, deshalb mit cUrl in fancy
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // Original: curl -H "Authorization: Bearer ABC" -X POST 'https://api.twitch.tv/helix/webhooks/hub?hub.callback=https://mars.fsoj.de/twitchlog/hookFollower.php&hub.mode=subscribe&hub.topic=https://api.twitch.tv/helix/users/follows?first=1%26to_id=120113992&hub.lease_seconds=864000'


        $subBool = $subscribe ? 'subscribe' : 'unsubscribe';
        $refUrlBase = Utils::$refUrlBase;


        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://api.twitch.tv/helix/webhooks/hub?hub.callback=${refUrlBase}hookBanChangeEvent.php&hub.mode=$subBool&hub.topic=https://api.twitch.tv/helix/moderation/banned/events?broadcaster_id=$userId%26first=1&hub.lease_seconds=864000");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = "Authorization: Bearer $appToken";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        
        return $result;
    }

    static function getAppAuth()
    {
        $url = 'https://id.twitch.tv/oauth2/token';
        $data = array(
            'client_id'      => Utils::$clientId,
            'client_secret'    => Utils::$clientSecret,
            'grant_type' => 'client_credentials',
            'scope' => 'moderation:read'
        );

        $options = array(
            'http' => array(
                'method'  => 'POST',
                'content' => http_build_query($data),
                'header' =>  "Content-type: application/x-www-form-urlencoded\r\n"
            )
        );

        $context  = stream_context_create($options);
        $result = file_get_contents($url, false, $context);
        $response = json_decode($result, true);

        if ($response === FALSE) {
            echo 'Fehler beim holen der Infos!';
        }
        return $response;
    }

    static function getWebhookSubscriptions($appToken)
    {
        $url = 'https://api.twitch.tv/helix/webhooks/subscriptions';

        $options = array(
            'http' => array(
                'method'  => 'GET',
                'header' =>  "Authorization: Bearer $appToken\r\n"
            )
        );

        $context  = stream_context_create($options);
        $result = file_get_contents($url, false, $context);
        $response = json_decode($result, true);

        if ($response === FALSE) {
            echo 'Fehler beim holen der Infos!';
        } else {
            return $response;
        }
    }
}
